[package]
name = "serde_gura"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
gura = "0.3.4"
indexmap = "1.7.0"

[dev-dependencies]
serde_derive = "1.0"